"""
Pompeii-Agent 对外包：装配与配置均从本包导入；底层扩展见 ``pompeii_agent.advanced``。
"""

from __future__ import annotations

from pompeii_agent.builders import (
    AgentBuilder,
    DeviceRoute,
    KernelBuilder,
    MemoryBuilder,
    ModelProviderBuilder,
    ModelRegistryBuilder,
    ResourceAccessBuilder,
    RuntimeBuilder,
    SecurityBuilder,
    SessionBuilder,
    SessionLimitsBuilder,
    ToolBuilder,
)
from pompeii_agent.config import (
    ConfigProvider,
    ModelRegistry,
    SessionConfig,
    bundled_config_dir,
    bundled_model_providers_path,
    bundled_session_defaults_path,
    load_model_registry_yaml,
    load_session_config_yaml,
    session_provider_from_yaml,
)
from pompeii_agent.facade import (
    HttpAgentService,
    InputDTO,
    create_http_service,
    create_interactive_port,
    create_kernel,
    framework_root,
    invoke_kernel,
    resources_root,
)
from pompeii_agent.advanced import (
    # Tool subsystem
    ToolHandler,
    ToolModuleImpl,
    ToolModule,
    load_tool_handler,
    McpToolBridge,
    ToolNetworkPolicyConfig,
    DeviceBackend,
    DeviceExecutionResult,
    LocalSimulatorBackend,
    CompositeDeviceBackend,
    device_result_to_tool_result,
    HttpUrlGuardError,
    assert_safe_http_tool_url,
    enforce_http_url_policy,
    ToolPluginDiscoveryError,
    discover_entrypoint_handlers,
    assert_tool_handler_signature,
    ToolRegistryConfig,
    DeviceToolRoute,
    ToolRegistryLoaderError,
    ToolRegistrySource,
    load_tool_registry_config,
    # MCP
    McpRuntimeConfig,
    McpServerEntry,
    McpHttpServerEntry,
    McpConfigSource,
    McpConfigLoaderError,
    McpBridgeRegistryError,
    resolve_mcp_bridge,
    McpStdioBridge,
    McpMultiStdioBridge,
    McpHttpBridge,
    McpMultiHttpBridge,
    # Device backend registry
    NoopDeviceBackend,
    DeviceBackendFactory,
    resolve_device_backend,
    build_device_backend,
    # Builtin handlers
    echo_handler,
    calc_handler,
    now_handler,
    make_http_get_handler,
    # User intent
    Chat,
    SystemHelp,
    SystemSummary,
    SystemArchive,
    SystemRemember,
    SystemForget,
    SystemPreference,
    SystemFact,
    SystemDelegate,
    ToolEcho,
    ToolTakePhoto,
    ToolPing,
    ToolAdd,
    UserIntent,
    # Port interaction modes
    CliMode,
    CliEmitter,
    WsMode,
    HttpMode,
    # Port events
    PortEvent,
    StreamDeltaEvent,
    ReplyEvent,
    ErrorEvent,
    StatusEvent,
    PolicyNoticeEvent,
    ConfirmationEvent,
    DelegateEvent,
    DeviceRequestEvent,
    # Port inputs
    PortInput,
    UserMessageInput,
    SystemCommandInput,
    DeviceResultInput,
    # Port helpers
    parse_user_intent,
    cli_request_factory,
    http_request_factory,
    ws_request_factory,
    session_request_factory,
    HttpEmitter,
    # Session types
    Session,
    SessionConfig,
    SessionLimits,
    SessionManager,
    SessionManagerImpl,
    SessionStats,
    SessionStatus,
    SessionStore,
    Message,
    Part,
    # Also re-export core types / builders from advanced
    AgentCore,
    AgentCoreImpl,
    DeviceRequest,
    ToolCall,
    ToolResult,
    ModelProviderSource,
    SessionConfigSource,
    build_core,
)
from app.version import __version__

__all__ = [
    # Builders
    "AgentBuilder",
    "DeviceRoute",
    "KernelBuilder",
    "MemoryBuilder",
    "ModelProviderBuilder",
    "ModelRegistryBuilder",
    "ResourceAccessBuilder",
    "RuntimeBuilder",
    "SecurityBuilder",
    "SessionBuilder",
    "SessionLimitsBuilder",
    "ToolBuilder",
    # Tool subsystem — tool module
    "ToolHandler",
    "ToolModuleImpl",
    "ToolModule",
    "load_tool_handler",
    "McpToolBridge",
    "ToolNetworkPolicyConfig",
    # Builtin handlers
    "echo_handler",
    "calc_handler",
    "now_handler",
    "make_http_get_handler",
    # User intent
    "Chat",
    "SystemHelp",
    "SystemSummary",
    "SystemArchive",
    "SystemRemember",
    "SystemForget",
    "SystemPreference",
    "SystemFact",
    "SystemDelegate",
    "ToolEcho",
    "ToolTakePhoto",
    "ToolPing",
    "ToolAdd",
    "UserIntent",
    # Port interaction modes
    "CliMode",
    "CliEmitter",
    "WsMode",
    "HttpMode",
    # Port events
    "PortEvent",
    "StreamDeltaEvent",
    "ReplyEvent",
    "ErrorEvent",
    "StatusEvent",
    "PolicyNoticeEvent",
    "ConfirmationEvent",
    "DelegateEvent",
    "DeviceRequestEvent",
    # Port inputs
    "PortInput",
    "UserMessageInput",
    "SystemCommandInput",
    "DeviceResultInput",
    # Port helpers
    "parse_user_intent",
    "cli_request_factory",
    "http_request_factory",
    "ws_request_factory",
    "session_request_factory",
    "HttpEmitter",
    # Session types
    "Session",
    "SessionLimits",
    "SessionManager",
    "SessionManagerImpl",
    "SessionStats",
    "SessionStatus",
    "SessionStore",
    "Message",
    "Part",
    # Device backend
    "DeviceBackend",
    "DeviceExecutionResult",
    "LocalSimulatorBackend",
    "CompositeDeviceBackend",
    "device_result_to_tool_result",
    "NoopDeviceBackend",
    "DeviceBackendFactory",
    "resolve_device_backend",
    "build_device_backend",
    # URL guard
    "HttpUrlGuardError",
    "assert_safe_http_tool_url",
    "enforce_http_url_policy",
    # Plugin discovery
    "ToolPluginDiscoveryError",
    "discover_entrypoint_handlers",
    "assert_tool_handler_signature",
    # Tool registry config
    "ToolRegistryConfig",
    "DeviceToolRoute",
    "ToolRegistryLoaderError",
    "ToolRegistrySource",
    "load_tool_registry_config",
    # MCP
    "McpRuntimeConfig",
    "McpServerEntry",
    "McpHttpServerEntry",
    "McpConfigSource",
    "McpConfigLoaderError",
    "McpBridgeRegistryError",
    "resolve_mcp_bridge",
    "McpStdioBridge",
    "McpMultiStdioBridge",
    "McpHttpBridge",
    "McpMultiHttpBridge",
    # Core types
    "AgentCore",
    "AgentCoreImpl",
    "AgentPort",
    "AgentRequest",
    "AgentResponse",
    "AssemblyModule",
    "ConfigProvider",
    "GenericAgentPort",
    "HttpAgentService",
    "InputDTO",
    "InteractionMode",
    "ModelModule",
    "ModelRegistry",
    "ModelProviderSource",
    "PortEmitter",
    "RequestFactory",
    "ResponseReason",
    "ToolModule",
    # Facade / helpers
    "__version__",
    "bundled_config_dir",
    "bundled_model_providers_path",
    "bundled_session_defaults_path",
    "build_core",
    "create_http_service",
    "create_interactive_port",
    "create_kernel",
    "framework_root",
    "invoke_kernel",
    "load_model_registry_yaml",
    "load_session_config_yaml",
    "resources_root",
    "session_provider_from_yaml",
]
